# Introduction

This week we are returning to pandas to look at data cleaning practices in Python. Our goal is to be able to identify and handle common data issues like misformatted strings, missing or duplicated values, and consistency checks. 

The readings for this week are: 
* [Sections 3.4-3.7 and 3.10 of the Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html)
* The .pdf in this folder also has several reminders of the syntax

Like all of the other data types and structures we have studied so far, strings have their own sets of functions and methods that can be applied without loading in any additional packages. Beyond basic transformation of the characters, there are also functions for splitting, searching, and slicing strings.

In [1]:
my_string = 'Hello, world!'

In [2]:
my_string.upper()

'HELLO, WORLD!'

In [10]:
lower_string = my_string.lower()
print(lower_string)

hello, world!

In [6]:
my_string = my_string.title()

In [7]:
my_string

'Hello, World!'

In [13]:
"hello, world".startswith("H")

False

In [16]:
split_list = " hello, world".split(',')

In [14]:
" hello, world".split('l')

[' he', '', 'o, wor', 'd']

In [7]:
split_list

[' hello', ' world']

In [19]:
split_list[0] = split_list[0].strip()

In [20]:
split_list[1] = split_list[1].strip()

In [21]:
"-".join(split_list)

'hello-world'

In [10]:
my_string.count(", wor")

1

In [22]:
my_string.count("l")

3

In [23]:
"hello" in my_string

False

In [25]:
"Hello" in my_string

True

In [13]:
my_string.find("world")

7

In [16]:
my_string.find("x")

-1

In [35]:
my_string.index("x")

ValueError: substring not found

In [36]:
number_string = '123,456'

In [38]:
int(number_string)

ValueError: invalid literal for int() with base 10: '123,456'

In [41]:
split_number_string = number_string.split(',')
print(split_number_string)

['123', '456']

In [40]:
number = int(split_number_string[0]+split_number_string[1])
print(number)

123456

In [45]:
number_string = '1,543,293,593,192,403'
#number_string = '1543293593192403'
if ',' in number_string: 
    number = ''
    for part in number_string.split(','):
        number += part
    number = int(number)
    print(number)
else:
    print("There are no commas in that number")

1543293593192403

Pandas provides vectorized versions of most of the string functions that can be applied to entire columns as once. These are accessed with the `.str` syntax and mostly behave just as their regular counterparts.

In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("./Data/string_processing.csv")

In [48]:
df.head()

                Name  ZipCode                   Snack        Soda Unnamed: 4
0        SOPHIA GOOD   241481                    Eggs       Pepsi        NaN
1     SIANNA SPENCER   918992     Snickers       Bars        Coke        NaN
2      LULU BROWNING   477153              Candy Corn   Coca-Cola        NaN
3      MACAULY FROST   529572          Cheetos               Coke        NaN
4  ANNABELLA ALVAREZ   704066          Marmalade       Pepsi-Cola        NaN

In [49]:
df = df[["Name","ZipCode","Snack","Soda"]]

In [51]:
df.tail()

                 Name  ZipCode        Snack         Soda
25    Nadeem Townsend   161774      Popcorn         Coke
26   Zunairah Hibbert   138667      Cheetos         Coke
27  Tayyab Millington   494736    Pop corn     Coca-Cola
28        Kelsey Luna   545296     Pop corn        Pepsi
29       Zander Scott   971923   Applesauce        pepsi

In [52]:
df["Name"].str.title()

0           Sophia Good
1        Sianna Spencer
2         Lulu Browning
3         Macauly Frost
4     Annabella Alvarez
5        Teodor Charles
6           Aron Battle
7        Sienna Collier
8      Esme-Rose Bright
9          Stacey Morin
10           Carlie Key
11       Alberto Flores
12      Teddie Clarkson
13         Komal Burris
14        Sanna Holcomb
15         Percy Arnold
16         Rhydian Pate
17        Aleena Werner
18            Shay Neal
19       Shayaan Barnes
20         Daria Gibson
21       Jaimee Schmidt
22           Ria Norman
23        Kayley Alford
24           Milosz Day
25      Nadeem Townsend
26     Zunairah Hibbert
27    Tayyab Millington
28          Kelsey Luna
29         Zander Scott
Name: Name, dtype: object

In [54]:
df["New_Name"] = df["Name"].str.title()

In [55]:
df.head()

,Name,ZipCode,Snack,Soda,New_Name
0,SOPHIA GOOD,241481,Eggs,Pepsi,Sophia Good
1,SIANNA SPENCER,918992,Snickers Bars,Coke,Sianna Spencer
2,LULU BROWNING,477153,Candy Corn,Coca-Cola,Lulu Browning
3,MACAULY FROST,529572,Cheetos,Coke,Macauly Frost
4,ANNABELLA ALVAREZ,704066,Marmalade,Pepsi-Cola,Annabella Alvarez

In [56]:
df['Snack']

0                          Eggs
1           Snickers       Bars
2                    Candy Corn
3                Cheetos
4                Marmalade
5      Fruit by  the       foot
6                     Chocolate
7                      Cheerios
8                    M and Ms
9                       Cheetos
10                     Bananas
11           Bagels   with  jam
12              Graham Crackers
13              Graham Crackers
14           Graham Crackers
15              Graham Crackers
16                    Chocolate
17
18           Peanut Butter Cups
19              Animal Crackers
20                     GoldFish
21                     Goldfish
22                    Gold fish
23                  Gold Fish
24                  Gold   Fish
25                      Popcorn
26                      Cheetos
27                    Pop corn
28                     Pop corn
29                   Applesauce
Name: Snack, dtype: object

In [58]:
(df['Snack'].str.find('Gold')).map({-1:False,0:True})

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22     True
23     True
24     True
25    False
26    False
27    False
28    False
29    False
Name: Snack, dtype: bool

In [68]:
df['Snack'].str.find('Gold').map({-1:False,0:True})

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22     True
23     True
24     True
25    False
26    False
27    False
28    False
29    False
Name: Snack, dtype: bool

In [61]:
df.loc[df['Snack'].str.find('Gold').map({-1:False,0:True})]

              Name  ZipCode        Snack        Soda        New_Name
20    daria gibson   116700     GoldFish        coke    Daria Gibson
21  jaimee schmidt   971168     Goldfish  pepsi-cola  Jaimee Schmidt
22      Ria Norman   503193    Gold fish       Pepsi      Ria Norman
23   Kayley Alford    52248  Gold Fish          Coke   Kayley Alford
24      Milosz Day    64933  Gold   Fish   Coca-Cola      Milosz Day

In [63]:
df["Soda"]

0           Pepsi
1            Coke
2       Coca-Cola
3            Coke
4      Pepsi-Cola
5           pepsi
6           Pepsi
7            coke
8       coca-Cola
9       Coca-Cola
10          pepsi
11        Pepsi
12           Coke
13        Pepsi
14      Coca-Cola
15          Pespi
16           Coke
17      Cold Coke
18     Pepsi-cola
19      Coca-Cola
20           coke
21     pepsi-cola
22          Pepsi
23           Coke
24      Coca-Cola
25           Coke
26           Coke
27      Coca-Cola
28          Pepsi
29          pepsi
Name: Soda, dtype: object

In [64]:
df["Soda"].str.upper().str.startswith("P").replace([True,False],["Pepsi","Coke"])

0     Pepsi
1      Coke
2      Coke
3      Coke
4     Pepsi
5     Pepsi
6      Coke
7      Coke
8      Coke
9      Coke
10    Pepsi
11     Coke
12     Coke
13    Pepsi
14     Coke
15    Pepsi
16     Coke
17     Coke
18    Pepsi
19     Coke
20     Coke
21    Pepsi
22    Pepsi
23     Coke
24     Coke
25     Coke
26     Coke
27     Coke
28    Pepsi
29    Pepsi
Name: Soda, dtype: object

Beyond string operations, there are several other common types of data cleaning issues that pandas allows us to handle in a vectorized fashion. Missing values are represented with NaN (Not a Number) inside the dataframe and frequently one of our first cleaning decisions will be to decide whether we want to remove (drop) the missing data or fill it in with another value. Another common data issue is duplicate values, which may also need to be removed. We also might want to check that our data entries satisfies reasonable consistency checks on both the values and the data types

In [67]:
df = pd.read_csv("./Data/VA_VOTES.csv")

In [68]:
df.head()

   BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
0  5200653        89.0     4.0    4.0    0.0   100.00%     0.00%
1  5200368       159.0    67.0   45.0   22.0    67.16%    32.84%
2  5200971         4.0     0.0    0.0    0.0       NaN       NaN
3  5200269       112.0    77.0   15.0   62.0    19.48%    80.52%
4  5200516        72.0    62.0    3.0   59.0     4.84%    95.16%

In [69]:
df.loc[2,"R_Percent"]

nan

In [70]:
import numpy as np
np.nan

nan

In [71]:
df['D_Percent'].isnull()

0     False
1     False
2      True
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: D_Percent, Length: 100, dtype: bool

In [72]:
df[df['D_Percent'].isnull()].index

Int64Index([2, 10, 12, 17, 19, 28, 36, 40, 41, 47, 56, 73, 76, 86, 92], dtype='int64')

In [73]:
df_dropped = df.drop(df[df['D_Percent'].isnull()].index)

In [74]:
df_dropped

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
0   5200653        89.0     4.0    4.0    0.0   100.00%     0.00%
1   5200368       159.0    67.0   45.0   22.0    67.16%    32.84%
3   5200269       112.0    77.0   15.0   62.0    19.48%    80.52%
4   5200516        72.0    62.0    3.0   59.0     4.84%    95.16%
5   5200600       272.0     1.0    1.0    0.0   100.00%     0.00%
..      ...         ...     ...    ...    ...       ...       ...
95  5200939        54.0    52.0   25.0   27.0    48.08%    51.92%
96  5200779       364.0   131.0   63.0   68.0    48.09%    51.91%
97  5200929       284.0   240.0   66.0  180.0    25.00%    75.00%
98  5200913        66.0    53.0   13.0   40.0    24.53%    75.47%
99  5200923        16.0     4.0    1.0    3.0    25.00%    75.00%

[85 rows x 7 columns]

In [81]:
df.fillna(-100)

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
0   5200653        89.0     4.0    4.0    0.0   100.00%     0.00%
1   5200368       159.0    67.0   45.0   22.0    67.16%    32.84%
2   5200971         4.0     0.0    0.0    0.0      -100      -100
3   5200269       112.0    77.0   15.0   62.0    19.48%    80.52%
4   5200516        72.0    62.0    3.0   59.0     4.84%    95.16%
5   5200600       272.0     1.0    1.0    0.0   100.00%     0.00%
6   5200271        35.0    37.0    6.0   30.0    17.14%    82.86%
7   5200753       490.0   352.0  319.0   33.0    90.63%     9.38%
8   5200773        57.0    79.0   55.0   24.0    69.62%    30.38%
9   5200745         7.0    36.0    4.0    3.0    57.14%    42.86%
10  5200803         0.0     0.0    0.0    0.0      -100      -100
11  5200408       110.0    75.0   37.0   38.0    49.33%    50.67%
12  5200809         0.0     0.0    0.0    0.0      -100      -100
13  5200658       153.0    26.0    0.0   26.0     0.00%   100.00%
14  5200317       250.0   219.0  169.0   50.0    77.17%    22.83%
15  5200773        87.0    79.0   55.0   24.0    69.62%    30.38%
16  5200382        63.0    24.0    5.0   29.0    20.83%    79.17%
17  5200744         0.0     0.0    0.0    0.0      -100      -100
18  5200792        80.0     4.0    1.0    3.0    25.00%    75.00%
19  5200851         0.0     0.0    0.0    0.0      -100      -100
20  5200235       210.0    11.0    9.0    2.0    81.82%    18.18%
21  5200534       100.0    62.0   16.0   44.0    25.81%    74.19%
22  5200912        42.0     8.0    8.0    0.0   100.00%     0.00%
23  5200517        28.0     4.0    2.0    2.0    50.00%    50.00%
24  5200754       185.0    49.0   33.0   16.0    67.35%    32.65%
25  5200996       160.0    21.0   10.0   11.0    47.62%    52.38%
26  5200487       112.0    18.0 -100.0   16.0    11.11%    88.89%
27  5200383        36.0    17.0    1.0   16.0     5.88%    94.12%
28  5200513         0.0     0.0    0.0    0.0      -100      -100
29  5200805        28.0    11.0    9.0    2.0    81.82%    18.18%
..      ...         ...     ...    ...    ...       ...       ...
70  5200413        44.0    36.0   23.0   13.0    63.89%    36.11%
71  5200529       212.0   190.0  135.0   45.0    78.95%    21.05%
72  5200365        84.0    65.0   40.0   25.0    61.54%    38.46%
73  5200939         0.0     0.0    0.0    0.0      -100      -100
74  5200111       256.0   211.0   82.0  129.0    38.86%    61.14%
75  5200627        18.0    16.0    9.0    7.0    56.25%    43.75%
76  5200438         0.0     0.0    0.0    0.0      -100      -100
77  5200129       325.0    31.0    4.0   27.0    12.90%    87.10%
78  5200834       330.0   101.0   18.0   83.0    17.82%    82.18%
79  5200596        42.0    38.0   29.0    9.0    76.32%    23.68%
80  5200905       132.0    98.0   44.0   54.0    44.90%    55.10%
81  5200678        52.0     4.0    2.0    2.0    50.00%    50.00%
82  5200110       255.0   114.0   12.0  102.0    10.53%    89.47%
83  5200384       190.0    10.0    7.0    3.0    70.00%    30.00%
84  5200181        85.0    13.0    7.0    6.0    53.85%    46.15%
85  5200754      -100.0    32.0   14.0   18.0    43.75%    56.25%
86  5200838         0.0     0.0    0.0    0.0      -100      -100
87  5200044       180.0    51.0   14.0   37.0    27.45%    72.55%
88  5200990       105.0    14.0    4.0   10.0    28.57%    71.43%
89  5200255       201.0    16.0   12.0    4.0    75.00%    25.00%
90  5200033       200.0    47.0   20.0   27.0    42.55%    57.45%
91  5200680       195.0   153.0  135.0   18.0    88.24%    11.76%
92  5200495         0.0     0.0    0.0    0.0      -100      -100
93  5200455        40.0  -100.0    4.0    8.0    33.33%    66.67%
94  5200700       220.0   128.0    6.0  122.0     4.69%    95.31%
95  5200939        54.0    52.0   25.0   27.0    48.08%    51.92%
96  5200779       364.0   131.0   63.0   68.0    48.09%    51.91%
97  5200929       284.0   240.0   66.0  180.0    25.00%    75.00%
98  5200913        66.0    53.0   13.0   40.0    24.53%    75.47%
99  5200923        16.0     4.0    1.0    3.0    25.00%    75.00%

[100 rows x 7 columns]

In [76]:
df_dropped[df_dropped.duplicated()==True]

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
72  5200365        84.0    65.0   40.0   25.0    61.54%    38.46%

In [77]:
df_dropped[df_dropped["BLOCKID"]==5200365]

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
58  5200365        84.0    65.0   40.0   25.0    61.54%    38.46%
72  5200365        84.0    65.0   40.0   25.0    61.54%    38.46%

In [78]:
df_dropped = df_dropped.drop_duplicates()

In [79]:
df_dropped

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
0   5200653        89.0     4.0    4.0    0.0   100.00%     0.00%
1   5200368       159.0    67.0   45.0   22.0    67.16%    32.84%
3   5200269       112.0    77.0   15.0   62.0    19.48%    80.52%
4   5200516        72.0    62.0    3.0   59.0     4.84%    95.16%
5   5200600       272.0     1.0    1.0    0.0   100.00%     0.00%
..      ...         ...     ...    ...    ...       ...       ...
95  5200939        54.0    52.0   25.0   27.0    48.08%    51.92%
96  5200779       364.0   131.0   63.0   68.0    48.09%    51.91%
97  5200929       284.0   240.0   66.0  180.0    25.00%    75.00%
98  5200913        66.0    53.0   13.0   40.0    24.53%    75.47%
99  5200923        16.0     4.0    1.0    3.0    25.00%    75.00%

[84 rows x 7 columns]

In [80]:
df_dropped[df_dropped["BLOCKID"].duplicated(keep=False)]

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent
8   5200773        57.0    79.0   55.0   24.0    69.62%    30.38%
15  5200773        87.0    79.0   55.0   24.0    69.62%    30.38%
16  5200382        63.0    24.0    5.0   29.0    20.83%    79.17%
24  5200754       185.0    49.0   33.0   16.0    67.35%    32.65%
51  5200779        27.0     6.0    4.0    2.0    66.67%    33.33%
55  5200382        30.0    15.0    4.0   11.0    26.67%    73.33%
85  5200754         NaN    32.0   14.0   18.0    43.75%    56.25%
96  5200779       364.0   131.0   63.0   68.0    48.09%    51.91%

In [81]:
df_dropped = df_dropped.drop(8)

In [82]:
df_dropped = df_dropped.drop(85)

In [83]:
len(df_dropped["BLOCKID"].unique())

80

In [86]:
df_dropped['pop check'] = df["Population"] > df["Voters"]
df_dropped

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent  pop check
0   5200653        89.0     4.0    4.0    0.0   100.00%     0.00%       True
1   5200368       159.0    67.0   45.0   22.0    67.16%    32.84%       True
3   5200269       112.0    77.0   15.0   62.0    19.48%    80.52%       True
4   5200516        72.0    62.0    3.0   59.0     4.84%    95.16%       True
5   5200600       272.0     1.0    1.0    0.0   100.00%     0.00%       True
..      ...         ...     ...    ...    ...       ...       ...        ...
95  5200939        54.0    52.0   25.0   27.0    48.08%    51.92%       True
96  5200779       364.0   131.0   63.0   68.0    48.09%    51.91%       True
97  5200929       284.0   240.0   66.0  180.0    25.00%    75.00%       True
98  5200913        66.0    53.0   13.0   40.0    24.53%    75.47%       True
99  5200923        16.0     4.0    1.0    3.0    25.00%    75.00%       True

[82 rows x 8 columns]

In [85]:
df_dropped.loc[df_dropped['pop check']==False]

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent  pop check
6   5200271        35.0    37.0    6.0   30.0    17.14%    82.86%      False
9   5200745         7.0    36.0    4.0    3.0    57.14%    42.86%      False
60  5200934         NaN     7.0    2.0    5.0    28.57%    71.43%      False
93  5200455        40.0     NaN    4.0    8.0    33.33%    66.67%      False

In [92]:
df_dropped.loc[df_dropped["D_GOV"]+df_dropped["R_GOV"] != df_dropped["Voters"]]

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent  pop check
6   5200271        35.0    37.0    6.0   30.0    17.14%    82.86%      False
9   5200745         7.0    36.0    4.0    3.0    57.14%    42.86%      False
16  5200382        63.0    24.0    5.0   29.0    20.83%    79.17%       True
21  5200534       100.0    62.0   16.0   44.0    25.81%    74.19%       True
26  5200487       112.0    18.0    NaN   16.0    11.11%    88.89%       True
46  5200829       279.0   237.0 -170.0  -67.0    71.73%    28.27%       True
50  5200790       150.0    84.0  -83.0    1.0    98.81%     1.19%       True
54  5200028        84.0    48.0   38.0    9.0    81.25%    18.75%       True
71  5200529       212.0   190.0  135.0   45.0    78.95%    21.05%       True
93  5200455        40.0     NaN    4.0    8.0    33.33%    66.67%      False
97  5200929       284.0   240.0   66.0  180.0    25.00%    75.00%       True

In [87]:
df_dropped.loc[26,"D_GOV"] = 2

In [88]:
df_dropped.loc[26]

BLOCKID       5200487
Population      112.0
Voters           18.0
D_GOV             2.0
R_GOV            16.0
D_Percent      11.11%
R_Percent      88.89%
pop check        True
Name: 26, dtype: object

In [89]:
df_dropped["D_GOV"] = df_dropped["D_GOV"].abs()

In [90]:
df_dropped["R_GOV"] = df_dropped["R_GOV"].abs()

In [91]:
df_dropped.loc[df_dropped["D_GOV"]+df_dropped["R_GOV"] != df_dropped["Voters"]]

    BLOCKID  Population  Voters  D_GOV  R_GOV D_Percent R_Percent  pop check
6   5200271        35.0    37.0    6.0   30.0    17.14%    82.86%      False
9   5200745         7.0    36.0    4.0    3.0    57.14%    42.86%      False
16  5200382        63.0    24.0    5.0   29.0    20.83%    79.17%       True
21  5200534       100.0    62.0   16.0   44.0    25.81%    74.19%       True
54  5200028        84.0    48.0   38.0    9.0    81.25%    18.75%       True
71  5200529       212.0   190.0  135.0   45.0    78.95%    21.05%       True
93  5200455        40.0     NaN    4.0    8.0    33.33%    66.67%      False
97  5200929       284.0   240.0   66.0  180.0    25.00%    75.00%       True