# Introduction

This week we are going to begin our exploration of one of  the main Python packages for data analysis: Pandas. Pandas  (which is short for Panel Data Analysis) is a package built for analyzing many types of tabular data that comes in rows and columns. It has efficient methods for loading, storing, modifying, and analyzing this type of data and is one of the key pieces of the Python analytics toolkit. We will return to pandas several times throughout the semester to perform increasingly complex operations on our datasets.  

The readings for this week are: 
* [Sections 3.1-3.3 of the Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html)
* You might also want to look at [this notebook](https://nbviewer.jupyter.org/github/pydata/pydata-book/blob/2nd-edition/ch05.ipynb) for additional examples

In [2]:
import pandas as pd

Since pandas is a separate module, we need to start by importing it. The standard shorthand for pandas is `pd` so we will use that syntax throughout this module. Pandas provides a couple of data structures that we will use quite a bit. The first is the Series, which we will use to represent columns of data. The Series is similar to the list and tuple structures that we encountered in the previous notebook. They also support a large collection of functions for automatically processing the data they contain. Description of these methods can be found in the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html).

In [3]:
my_first_column = pd.Series([1,10,3,5,9,3,2,2,1])

In [4]:
my_first_column

0     1
1    10
2     3
3     5
4     9
5     3
6     2
7     2
8     1
dtype: int64

The first thing to notice is that pandas has automatically created an index for us - this will be a very useful feature when we are dealing with larger, more complex datasets. It also tells us what type of data is stored in the Series. To access individual elements in the Series, we can use a similar syntax to lists and tuples or appeal to the index directly with the `.iloc` attribute.

In [5]:
my_first_column[3]

5

In [6]:
my_first_column[-1]

KeyError: -1

In [8]:
my_first_column.loc[3]

5

In [19]:
my_first_column.iloc[-1]

1

In [9]:
my_first_column.index = ['a','b','c','d','e','f','g','h','i']

In [10]:
my_first_column

a     1
b    10
c     3
d     5
e     9
f     3
g     2
h     2
i     1
dtype: int64

In [72]:
my_first_column.loc['d']

5

In [27]:
my_second_column = pd.Series([5,44,2,1,0,0,3,4,6])

In [28]:
my_second_column.max()

44

In [29]:
my_second_column.sum()

65

In [30]:
my_second_column.mean()

7.222222222222222

We can group columns of data together into larger collections called dataframes. These will be our standard structure for interacting with all sorts of data examples. For now, we will think of these as labelled columns of data, where each data is represented by a Series. This matches the standard presentation of data as observations (rows) and variable (columns). As with Series, dataframes come with many useful methods that will make our lives easier, documented [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html).

In [16]:
#Data source: https://www.collegetuitioncompare.com/
tuition_df =pd.DataFrame({"WSU":[27302,27697,28206,27825,26899,27249,27484,27991,28520],
                          "UI":[19700,19598,19630,20294,20640,21300,21350,21820,21820],
                         "year":[2012,2013,2014,2015,2016,2017,2018,2019,2020]})

In [17]:
tuition_df

     WSU     UI  year
0  27302  19700  2012
1  27697  19598  2013
2  28206  19630  2014
3  27825  20294  2015
4  26899  20640  2016
5  27249  21300  2017
6  27484  21350  2018
7  27991  21820  2019
8  28520  21820  2020

In [18]:
tuition_df =pd.DataFrame({"WSU":[27302,27697,28206,27825,26899,27249,27484,27991,28520],
                          "UI":[19700,19598,19630,20294,20640,21300,21350,21820,21820]},
                         index=[2012,2013,2014,2015,2016,2017,2018,2019,2020])

In [19]:
tuition_df

        WSU     UI
2012  27302  19700
2013  27697  19598
2014  28206  19630
2015  27825  20294
2016  26899  20640
2017  27249  21300
2018  27484  21350
2019  27991  21820
2020  28520  21820

In [20]:
tuition_df.columns

Index(['WSU', 'UI'], dtype='object')

In [32]:
column_dictionary = {
    'Column 1':my_first_column,
    'Column 2':my_second_column
}

In [36]:
my_second_df = pd.DataFrame(column_dictionary)

In [37]:
my_second_df

   Column 1  Column 2
a         1         5
b        10        44
c         3         2
d         5         1
e         9         0
f         3         0
g         2         3
h         2         4
i         1         6

In [35]:
my_second_column.index = ['a','b','c','d','e','f','g','h','i']

In [38]:
tuition_df.mean()

WSU    27685.888889
UI     20683.555556
dtype: float64

In [39]:
tuition_df.head()

        WSU     UI
2012  27302  19700
2013  27697  19598
2014  28206  19630
2015  27825  20294
2016  26899  20640

In [40]:
tuition_df.tail()

        WSU     UI
2016  26899  20640
2017  27249  21300
2018  27484  21350
2019  27991  21820
2020  28520  21820

In [88]:
tuition_df.describe()

                WSU            UI
count      9.000000      9.000000
mean   27685.888889  20683.555556
std      509.536663    923.079508
min    26899.000000  19598.000000
25%    27302.000000  19700.000000
50%    27697.000000  20640.000000
75%    27991.000000  21350.000000
max    28520.000000  21820.000000

Accessing individual elements in dataframes requires us to specify both a row and a column but we will also sometimes want to access full rows or columns as well.

In [43]:
my_second_df.loc['f']

Column 1    3
Column 2    0
Name: f, dtype: int64

In [44]:
my_second_df.loc['a']

Column 1    1
Column 2    5
Name: a, dtype: int64

In [45]:
my_second_df.iloc[5]

Column 1    3
Column 2    0
Name: f, dtype: int64

In [48]:
tuition_df['WSU']

2012    27302
2013    27697
2014    28206
2015    27825
2016    26899
2017    27249
2018    27484
2019    27991
2020    28520
Name: WSU, dtype: int64

In [93]:
tuition_df['WSU'][2012]

27302

In [96]:
tuition_df.loc[2012,"WSU"]

27302

If we had to create all of our dataframes by hand that would be remarkably inefficient. Instead, we will usually load in complete datasets stored as .csv files. These can either be stored on our computer locally or downloaded diectly from the internet. If we are loading data locally, we need to be careful to get the right directory.

In [49]:
HWAS = pd.read_csv("./Height_Weight_Age_Sex.csv")

In [51]:
len(HWAS)

544

In [50]:
HWAS.head()

    height     weight   age  male
0  151.765  47.825606  63.0     1
1  139.700  36.485807  63.0     0
2  136.525  31.864838  65.0     0
3  156.845  53.041914  41.0     1
4  145.415  41.276872  51.0     0

In [103]:
HWAS.describe()

           height      weight         age        male
count  544.000000  544.000000  544.000000  544.000000
mean   138.263596   35.610618   29.344393    0.472426
std     27.602448   14.719178   20.746888    0.499699
min     53.975000    4.252425    0.000000    0.000000
25%    125.095000   22.007717   12.000000    0.000000
50%    148.590000   40.057844   27.000000    0.000000
75%    157.480000   47.209005   43.000000    1.000000
max    179.070000   62.992589   88.000000    1.000000

In [52]:
HWAS[HWAS['male']==1]

      height     weight   age  male
0    151.765  47.825606  63.0     1
3    156.845  53.041914  41.0     1
5    163.830  62.992589  35.0     1
7    168.910  55.479971  27.0     1
9    165.100  54.487739  54.0     1
..       ...        ...   ...   ...
538   76.835   8.022908   1.0     1
539  145.415  31.127751  17.0     1
540  162.560  52.163080  31.0     1
542   71.120   8.051258   0.0     1
543  158.750  52.531624  68.0     1

[257 rows x 4 columns]

In [55]:
HWAS[HWAS['male']==1]["weight"].mean()

38.02624089610895

In [56]:
HWAS[HWAS['male']==0]["weight"].mean()

33.44749846689897

In [57]:
cost_of_living = pd.read_csv("./COL.csv")

FileNotFoundError: [Errno 2] No such file or directory: './COL.csv'

In [58]:
cost_of_living = pd.read_csv("./Data/COL.csv")

In [59]:
cost_of_living.tail()

,City,Cappuccino,Cinema,Wine,Gasoline,Avg Rent,Avg Disposable Income
211,Davao,0.79,1.90,3.17,0.84,554.18,158.34
212,Karachi,1.00,3.27,5.11,0.67,197.78,139.60
213,Lahore,1.23,3.27,6.54,0.66,206.08,132.95
214,Addis Ababa,0.46,2.29,4.18,0.72,653.77,124.22
215,Indore,0.91,2.23,6.03,0.84,205.15,120.68

In [60]:
GME = pd.read_csv("http://math.wsu.edu/faculty/ddeford/GME_Stock.csv")

In [61]:
GME

,Date,Open,High,Low,Close,Adj Close,Volume
0,2/4/2020,4.030000,4.250000,3.970000,4.070000,4.070000,3563100
1,2/5/2020,4.150000,4.410000,4.140000,4.180000,4.180000,2641700
2,2/6/2020,4.200000,4.300000,4.140000,4.140000,4.140000,1510300
3,2/7/2020,4.110000,4.130000,3.770000,3.810000,3.810000,2742300
4,2/10/2020,3.850000,4.100000,3.740000,3.940000,3.940000,2777000
...,...,...,...,...,...,...,...
248,1/28/2021,265.000000,483.000000,112.250000,193.600006,193.600006,58815800
249,1/29/2021,379.709991,413.980011,250.000000,325.000000,325.000000,50259200
250,2/1/2021,316.559998,322.000000,212.000000,225.000000,225.000000,37382200
251,2/2/2021,140.759995,158.000000,74.220001,90.000000,90.000000,78183100
252,2/3/2021,112.010002,113.400002,85.250000,92.410004,92.410004,42463800

In [62]:
GME.index = GME["Date"]

In [63]:
GME.head()

                Date  Open  High   Low  Close  Adj Close   Volume
Date
2/4/2020    2/4/2020  4.03  4.25  3.97   4.07       4.07  3563100
2/5/2020    2/5/2020  4.15  4.41  4.14   4.18       4.18  2641700
2/6/2020    2/6/2020  4.20  4.30  4.14   4.14       4.14  1510300
2/7/2020    2/7/2020  4.11  4.13  3.77   3.81       3.81  2742300
2/10/2020  2/10/2020  3.85  4.10  3.74   3.94       3.94  2777000

In [64]:
GME["Open"]

Date
2/4/2020       4.030000
2/5/2020       4.150000
2/6/2020       4.200000
2/7/2020       4.110000
2/10/2020      3.850000
                ...
1/28/2021    265.000000
1/29/2021    379.709991
2/1/2021     316.559998
2/2/2021     140.759995
2/3/2021     112.010002
Name: Open, Length: 253, dtype: float64